### ISSUE TITLE
Inconsistent failure "Cannot read property 'statusCode' of undefined"

### ISSUE THREAD

**Issue by mrlacey** [restqa/404-links#4]
I've been using this fine for the last few months but am now getting inconsistent failures on valid/working URIs. (Not always the same ones.)

The error message is: 

```ascii
/restqa/src/urls.js:15
      const statusCode = (err && err.code) || response.statusCode
                                                       ^

TypeError: Cannot read property 'statusCode' of undefined
    at Request.request.get [as _callback] (/restqa/src/urls.js:15:56)
    at self.callback (/restqa/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.init (/restqa/node_modules/request/request.js:273:17)
    at new Request (/restqa/node_modules/request/request.js:127:8)
    at request (/restqa/node_modules/request/index.js:53:10)
    at Function.get (/restqa/node_modules/request/index.js:61:12)
    at /restqa/src/urls.js:13:13
    at queue (/restqa/node_modules/async/dist/async.js:3206:13)
    at Object.process (/restqa/node_modules/async/dist/async.js:1432:21)
```

**Comment by olivierodo** [comment]
Hello let me take a look at it
